### ISSUE TITLE
Roadmap contexts

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/docker-hive#36]
# Contexts
## 2. Consistency & Resilience

- [ ] Canary deployments & Rolling upgrades #35 
- [x] Volumes (nomad context) #37 
- [ ]  Backup and recovery if containers failure (#38 )
- [x] Deploy with attached(existing) volume (part of #37 )
- ... (you name it)
## 3. Security
- [x] Encryption in transit, service-mesh communication managment (covered by side-car proxies and intentions) #44 
- [x]  Delegate admin role to vault, to generate dynamic credentatial with short TTL. secrets engine. (#42 #40 #41 #39 )
> - [x] minio kv [#16](https://github.com/fredrikhgrelland/terraform-nomad-minio/issues/16)
> - [x] postgres kv [#12](https://github.com/fredrikhgrelland/terraform-nomad-postgres/issues/12)

- [x] Certification generation via Vault, PKI [#337 ](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/337)
- [ ]  Encryption at rest #46 
- [ ]  Policies (Admin/Produsent/consument) [#397](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/397)
- ... (you name it)
## 4. Scaling
- Deployment strategy (master-slave, horizontal, etc...)
- Dynamic/static scaling 
- ... (you name it)
## 5. Observability. How/Where to expose. Additional nodes
- Metrics (Prometheus, ...) and Pre-builded dash-boards(Grafana examples)
- Logs (Splunk, LogStash, ...)
- Traces (Zipkin, OpenCensus, ...)
- ... (you name it)
## 6. Cover needs of other teams
- Add new module (kafka, nifi, etc...)
- ... (you name it)
## 7. Enterprise features
- [ ]  Namespaces #43 
> - [x] consul namespaces [#346](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/346)
> - [x] vault namespaces [#353](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/353)
- [ ] Sentinel policies #45 
- ... (you name it)

**Comment by zhenik** [comment]
# Current priorities
- ### 2. Consistency & Resilience
- ### 3. Security
- ### 7. Enterprise features

**Comment by zhenik** [comment]
# 40 week priorities
- ### 3. Security - Policies (Admin/Produsent/consument) - Consul. User stories first. @zhenik
